# Generated by Django 3.0.3 on 2020-02-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('order_code', models.PositiveIntegerField()),
                ('file_url', models.URLField()),
                ('text', models.TextField(max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
