# Generated by Django 3.0.3 on 2020-02-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='file_url',
            field=models.URLField(null=True),
        ),
    ]
