# Generated by Django 3.0.3 on 2020-03-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20200228_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='file_url',
            field=models.ImageField(null=True, upload_to='images/support/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='order_code',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
